#!/usr/bin/env python3
"""
Daily New Books Digest
----------------------
Fetches recently published English books from Google Books API for each
configured category and creates a GitHub Issue as the daily digest.
The issue is assigned to the repo owner so GitHub sends an email notification.

No external secrets required — uses the built-in GITHUB_TOKEN.
"""

import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CATEGORIES_FILE = ROOT / "categories.yml"
BOOKS_PER_CATEGORY = 5


# ── Google Books ───────────────────────────────────────────────────────────────

def _fetch(query: str) -> list[dict]:
    """Single Google Books API call, returns raw book dicts."""
    params = {
        "q":           query,
        "orderBy":     "newest",
        "maxResults":  40,
        "printType":   "books",
        "langRestrict": "en",
    }
    url = "https://www.googleapis.com/books/v1/volumes?" + urllib.parse.urlencode(params)
    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            return json.loads(resp.read()).get("items", [])
    except Exception as exc:
        print(f"[WARN] API error for '{query}': {exc}")
        return []


def google_books_search(queries: list[str], want: int) -> list[dict]:
    """Search multiple queries, deduplicate by title, return up to want books."""
    seen: set[str] = set()
    books: list[dict] = []

    for query in queries:
        for item in _fetch(query):
            info = item.get("volumeInfo", {})
            title = info.get("title", "").strip()
            if not title or title.lower() in seen:
                continue
            seen.add(title.lower())

            desc = info.get("description", "")
            if len(desc) > 350:
                desc = desc[:347] + "..."

            books.append({
                "title":         title,
                "authors":       ", ".join(info.get("authors", ["Unknown Author"])),
                "published":     info.get("publishedDate", ""),
                "description":   desc,
                "link":          info.get("infoLink", ""),
                "rating":        info.get("averageRating", 0),
                "ratings_count": info.get("ratingsCount", 0),
            })

        if len(books) >= want:
            break

    return books[:want]


# ── Formatting ─────────────────────────────────────────────────────────────────

def format_book(book: dict) -> str:
    rating_str = ""
    if book["rating"]:
        rating_str = f" · ⭐ {book['rating']}/5 ({book['ratings_count']} ratings)"

    lines = [f"### [{book['title']}]({book['link']})"]
    lines.append(f"**{book['authors']}**" + (f" · {book['published']}" if book["published"] else "") + rating_str)
    if book["description"]:
        lines.append("")
        lines.append(book["description"])
    lines.append("")
    return "\n".join(lines)


def build_issue_body(sections: dict[str, list], date_str: str) -> str:
    total = sum(len(v) for v in sections.values())
    body = (
        f"# \U0001f4da Daily New Books Digest\n"
        f"**{date_str}**\n\n"
        f"> {total} new English books across {len(sections)} categories\n\n"
        "---\n\n"
    )
    for name, books in sections.items():
        if not books:
            continue
        body += f"## {name}\n\n"
        for book in books:
            body += format_book(book)
        body += "---\n\n"
    body += "*Generated by [nevzatalkan/new-books](https://github.com/nevzatalkan/new-books)*"
    return body


# ── GitHub Issue ───────────────────────────────────────────────────────────────

def create_github_issue(title: str, body: str, owner: str) -> None:
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    repo  = os.environ.get("GITHUB_REPOSITORY", "").strip()

    if not token or not repo:
        print("[ERROR] GITHUB_TOKEN or GITHUB_REPOSITORY is not set.", file=sys.stderr)
        sys.exit(1)

    payload = json.dumps({
        "title":     title,
        "body":      body,
        "assignees": [owner],
    }).encode()

    req = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/issues",
        data=payload,
        headers={
            "Authorization":        f"Bearer {token}",
            "Accept":               "application/vnd.github+json",
            "Content-Type":         "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            issue = json.loads(resp.read())
            print(f"[OK] Issue created: {issue['html_url']}")
    except urllib.error.HTTPError as exc:
        print(f"[ERROR] GitHub API: {exc.read().decode()}", file=sys.stderr)
        sys.exit(1)


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    with open(CATEGORIES_FILE, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    categories = [c for c in data.get("categories", []) if c.get("active")]
    if not categories:
        print("[WARN] No active categories in categories.yml")
        sys.exit(0)

    repo_env = os.environ.get("GITHUB_REPOSITORY", "/")
    owner = repo_env.split("/")[0]

    sections: dict[str, list] = {}
    for cat in categories:
        queries = cat.get("queries", [])
        if not queries:
            continue
        print(f"[INFO] Searching: {cat['name']}  ({len(queries)} queries)")
        books = google_books_search(queries, want=BOOKS_PER_CATEGORY)
        sections[cat["name"]] = books
        print(f"       Found {len(books)} books")

    total = sum(len(v) for v in sections.values())
    print(f"[INFO] Total: {total} books in {len(sections)} categories")

    today    = datetime.now(tz=timezone.utc)
    date_str = today.strftime("%-d %B %Y")

    create_github_issue(
        title=f"\U0001f4da Daily Books Digest \u2014 {date_str}",
        body=build_issue_body(sections, date_str),
        owner=owner,
    )


if __name__ == "__main__":
    main()
