#!/usr/bin/env python3
"""
Daily New Books Digest
----------------------
Fetches newly published English books from Google Books API for each
configured category and creates a GitHub Issue as the daily digest.
The issue is assigned to the repo owner so GitHub sends an email notification.

No external secrets required — uses the built-in GITHUB_TOKEN.
"""

import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CATEGORIES_FILE = ROOT / "categories.yml"
BOOKS_PER_CATEGORY = 5
MIN_YEAR = datetime.now().year - 2  # include books from last 2 years


# ── Google Books ───────────────────────────────────────────────────────────────

def google_books_search(query: str, max_results: int = 15) -> list[dict]:
    """Return up to max_results recent English books matching query."""
    params = {
        "q": query,
        "orderBy": "newest",
        "maxResults": min(max_results, 40),
        "printType": "books",
        "langRestrict": "en",
    }
    url = "https://www.googleapis.com/books/v1/volumes?" + urllib.parse.urlencode(params)

    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            data = json.loads(resp.read())
    except Exception as exc:
        print(f"[WARN] Google Books API error for '{query}': {exc}")
        return []

    books = []
    for item in data.get("items", []):
        info = item.get("volumeInfo", {})
        pub_date = info.get("publishedDate", "")
        if pub_date:
            try:
                if int(pub_date[:4]) < MIN_YEAR:
                    continue
            except ValueError:
                pass

        desc = info.get("description", "")
        if len(desc) > 300:
            desc = desc[:297] + "..."

        books.append({
            "title":         info.get("title", "Unknown Title"),
            "authors":       ", ".join(info.get("authors", ["Unknown Author"])),
            "published":     pub_date,
            "description":   desc,
            "link":          info.get("infoLink", ""),
            "rating":        info.get("averageRating", 0),
            "ratings_count": info.get("ratingsCount", 0),
        })

    return books


# ── Formatting ─────────────────────────────────────────────────────────────────

def format_book(book: dict) -> str:
    rating_str = ""
    if book["rating"]:
        rating_str = f" · ⭐ {book['rating']}/5 ({book['ratings_count']} ratings)"

    lines = [f"### [{book['title']}]({book['link']})"]
    lines.append(f"**{book['authors']}** · {book['published']}{rating_str}")
    if book["description"]:
        lines.append("")
        lines.append(book["description"])
    lines.append("")
    return "\n".join(lines)


def build_issue_body(sections: dict[str, list], date_str: str) -> str:
    total = sum(len(v) for v in sections.values())
    body = (
        f"# \U0001f4da Daily New Books Digest\n"
        f"**{date_str}**\n\n"
        f"> {total} new English books across {len(sections)} categories · "
        f"Published {MIN_YEAR}+\n\n"
        "---\n\n"
    )
    for name, books in sections.items():
        if not books:
            continue
        body += f"## {name}\n\n"
        for book in books:
            body += format_book(book)
        body += "---\n\n"
    body += "*Generated by [nevzatalkan/new-books](https://github.com/nevzatalkan/new-books)*"
    return body


# ── GitHub Issue ───────────────────────────────────────────────────────────────

def create_github_issue(title: str, body: str, owner: str) -> None:
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    repo  = os.environ.get("GITHUB_REPOSITORY", "").strip()

    if not token or not repo:
        print("[ERROR] GITHUB_TOKEN or GITHUB_REPOSITORY is not set.", file=sys.stderr)
        sys.exit(1)

    payload = json.dumps({
        "title":     title,
        "body":      body,
        "assignees": [owner],   # triggers email to the assignee
    }).encode()

    req = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/issues",
        data=payload,
        headers={
            "Authorization":        f"Bearer {token}",
            "Accept":               "application/vnd.github+json",
            "Content-Type":         "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            issue = json.loads(resp.read())
            print(f"[OK] Issue created: {issue['html_url']}")
    except urllib.error.HTTPError as exc:
        print(f"[ERROR] GitHub API: {exc.read().decode()}", file=sys.stderr)
        sys.exit(1)


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    with open(CATEGORIES_FILE, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    categories = [c for c in data.get("categories", []) if c.get("active")]
    if not categories:
        print("[WARN] No active categories in categories.yml")
        sys.exit(0)

    # Derive owner from "owner/repo" string
    repo_env = os.environ.get("GITHUB_REPOSITORY", "/")
    owner = repo_env.split("/")[0]

    sections: dict[str, list] = {}
    for cat in categories:
        query = cat.get("query", "")
        if not query:
            continue
        print(f"[INFO] Searching: {cat['name']}  →  {query}")
        books = google_books_search(query, max_results=BOOKS_PER_CATEGORY + 10)
        sections[cat["name"]] = books[:BOOKS_PER_CATEGORY]
        print(f"       Found {len(sections[cat['name']])} books")

    total = sum(len(v) for v in sections.values())
    print(f"[INFO] Total: {total} books in {len(sections)} categories")

    today    = datetime.now(tz=timezone.utc)
    date_str = today.strftime("%-d %B %Y")

    create_github_issue(
        title=f"\U0001f4da Daily Books Digest \u2014 {date_str}",
        body=build_issue_body(sections, date_str),
        owner=owner,
    )


if __name__ == "__main__":
    main()
